version: '1'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: opencart
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: opencart_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./app:/usr/share/nginx/html:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./nginx/server.crt:/etc/nginx/server.crt
      - ./nginx/server.key:/etc/nginx/server.key
      - ./logs/nginx:/var/log/nginx/:rw
    networks:
      - app-network

  fpm:
    container_name: fpm
    build: ./php-fpm
    ports:
      - '9000'
    volumes:
      - ./app:/usr/share/nginx/html:rw
      - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:rw
      - ./logs/php-fpm:/tmp:rw
    networks:
      - app-network  

networks:
  app-network:   